version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "lab21"
      POSTGRES_USER: "ksv"
      POSTGRES_PASSWORD: "superstrongpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - lab21_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ksv -d lab21"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  lab21_postgres_data: